name: flutter_gen
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 5.3.3
homepage: https://github.com/FlutterGen/flutter_gen
repository: https://github.com/FlutterGen/flutter_gen
documentation: https://github.com/FlutterGen/flutter_gen
issue_tracker: https://github.com/FlutterGen/flutter_gen/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

executables:
  fluttergen: flutter_gen_command

dependencies:
  #  flutter_gen_core: 5.3.3
  flutter_gen_core:
    git:
      url: https://github.com/perc-solutions/flutter_gen.git
      path: packages/core
      ref: feature/add-app-resources-gen
  args: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  test_process: ^2.0.0
